### ISSUE TITLE
Add animation class

### ISSUE THREAD

**Issue by SplittyDev** [splitandthechro/nginz#14]
Currently animations have to be done manually.
- Add an animator class to be able to easily animate textures and sprites
- Create a custom content loader for animated textures

**Comment by chronium** [comment]
Related to this, there isn't a good way to implement animations.
Each sprite sheet might have animations done in a different way, or maybe there is some logic behind.
Basically, we'll put this on hold for a while.

**Comment by SplittyDev** [comment]
@chronium I implemented a Animator class that works with a SpriteSheet2D instance.
It can definitely be improved but it works very well. You can set the start and end tile of the SpriteSheet, you can set the duration in seconds or milliseconds and you can even set up speed multipliers and stuff like that.

Curves would be nice to have in the future, but for the first milsestone this is gonna work.
Implemented in 9dc1575b21d644a8e0678ee3ef6c8e9fafa95d17.
